### ISSUE TITLE
Can't access to channel b 

### ISSUE THREAD

**Issue by thomasmuench** [PhilWaldmann/node-red-contrib-hubo#1]
i have configured 0 Inputs and 16 Outputs. I can only access to Port 0-1 (Channel A). 0x00 - 0x07
0x08 - 0x15 not working for channel B.

**Comment by PhilWaldmann** [comment]
What Hubo Rev. do you use? How many relays have you solderd on... I'll need more information about your setup to help you

**Comment by thomasmuench** [comment]
Not a Hubo Board. I tried to access directly a MCP23017 Chip whit 16 Output. No relais etc, only a testboard.

**Comment by PhilWaldmann** [comment]
You can find the docs for the MCP23017 [here](http://ww1.microchip.com/downloads/en/DeviceDoc/20001952C.pdf).
Debug it via [i2cdetect](https://linux.die.net/man/8/i2cdetect), [i2cset](https://linux.die.net/man/8/i2cset) and co. And [here](https://github.com/PhilWaldmann/node-red-contrib-hubo/blob/master/hubo.js#L33) is the relevant code to set an output channel via node-red-contrib-hubo.
